### SOFT SKILLS ENDPOINTS

### Получение всех групп софт скиллов
GET localhost:8080/specialist-profile/skills/soft/groups

### Изменение оценки софт скилла пользователя
PUT localhost:8080/specialist-profile/users/1/marks/soft
Content-Type: application/json

{
  "skill_id": 1,
  "mark": 3
}

### Получение всех оценок софт скиллов пользователя
GET localhost:8080/specialist-profile/users/1/marks/soft

### Получение всех софт скиллов по определенной группе
GET localhost:8080/specialist-profile/skills/soft/thinking


### HARD SKILLS ENDPOINTS

### Получение всех ролей
GET localhost:8080/specialist-profile/roles

### Получение всех оценок хард скиллов пользователя
GET localhost:8080/specialist-profile/users/1/marks/hard

### Изменение оценки хард скилла
PUT localhost:8080/specialist-profile/users/1/marks/hard
Content-Type: application/json

{
  "skill_id": 1,
  "mark": 3
}

### Получение всех хард скиллов для определенной роли
GET localhost:8080/specialist-profile/skills/hard/backend

### ADD SKILL ENDPOINTS

### Поиск подходящих доп скиллов по названию
POST localhost:8080/specialist-profile/skills/add/suitable
Content-Type: application/json

{
  "competence_name": "Алг"
}

### Добавление дополнительного скилла пользователю
POST localhost:8080/specialist-profile/users/1/skills/add
Content-Type: application/json

{
  "skill_name": "Что то",
  "role_id": 6
}

### Получение всех оценок доп скиллов пользователя
GET localhost:8080/specialist-profile/users/1/marks/add

### Изменение оценки доп скилла пользователя
PUT localhost:8080/specialist-profile/users/1/marks/add
Content-Type: application/json

{
  "skill_id": 1,
  "mark": 3
}

### USER ENDPOINTS

### Метод полкчения всех пользователей
GET localhost:8080/specialist-profile/users

### Метод получения общей информации о пользователе
GET localhost:8080/specialist-profile/users/general/1

### Метод получения рабочей информации о пользователе
GET localhost:8080/specialist-profile/users/working/1

### Поиск по ФИО
POST localhost:8080/specialist-profile/users
Content-Type: application/json

{
  "full_name": "Степ"
}

### CHECK BACKEND CONDITION
GET localhost:8080/actuator/mappings












