CREATE TABLE soft_skills
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name VARCHAR(512) UNIQUE             NOT NULL,
    group_id   INT REFERENCES soft_groups (id) NOT NULL
);