CREATE TABLE marks_of_users_soft_skills
(
    soft_mark_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INT REFERENCES users (id),
    skill_id     INT REFERENCES soft_skills (id),
    mark         INT DEFAULT 0 CHECK (mark IN (-1, 0, 1, 2, 3))
);