CREATE TABLE hard_skills
(
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name     VARCHAR(512) UNIQUE NOT NULL,
    grade_method   VARCHAR             NOT NULL,
    develop_method VARCHAR             NOT NULL
);