CREATE TABLE users
(
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR(128)                                     NOT NULL,
    last_name      VARCHAR(128)                                     NOT NULL,
    patronymic     VARCHAR(128),
    date_of_birth  DATE                                             NOT NULL,
    gender         VARCHAR CHECK (gender IN ('Мужской', 'Женский')) NOT NULL,
    location       VARCHAR(128)                                     NOT NULL,
    post_id        INT REFERENCES posts (id)                        NOT NULL,
    role_id        INT REFERENCES roles (id)                        NOT NULL,
    specialization VARCHAR(512)                                     NOT NULL
);