CREATE TABLE marks_of_users_hard_skills
(
    hard_mark_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INT REFERENCES users (id),
    skill_id     INT REFERENCES hard_skills (id),
    mark         INT DEFAULT 1 CHECK (mark IN (0, 1, 2, 3))
);