CREATE TABLE add_competences
(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(512) UNIQUE       NOT NULL,
    user_id INT REFERENCES users (id) NOT NULL,
    role_id INT REFERENCES roles (id) NOT NULL,
    mark    INT DEFAULT 1 CHECK (mark IN (0, 1, 2, 3))
);