scrape_configs:
  - job_name: 'SpecialistProfileMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '10.4.56.68:8080' ]
        labels:
          application: 'Specialist IT Profile Project'