spring:
  application:
    name: backend
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
server:
  port: 8080
  address: 0.0.0.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: /specialist-profile.*
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted 
      your API Request Quota\" }"
      rate-limits:
        - cache-key: "getHeader('X-user-id')"


